#!/bin/bash
case $1 in
    'init') root -l -b -q "record_discriminants.cxx(\"$2\", \"$3\")";;
    'hist') root -l -b -q "generate_plots.cxx(\"$2\", \"$3\", \"$4\")";;
    'roc')  root -l -b -q "roc_curves.cxx(\"$2\")";;
    *) echo 'Please provide a valid plot type';;
esac
 
