#!/bin/bash
source $1

if [[ -n $ttbar ]] && [[ -n $zprime ]]; then 
    export hybridtuning=1
elif [[ -n $ttbar ]]; then
    export eventtype=$ttbar
elif [[ -n $zprime ]]; then
    export eventtype=$zprime
else
    echo 'You need to define a sample!'
fi

if [[ -n $hybridtuning ]]; then
    export samples="${ttbar}_${size} ${zprime}_${size}"
    export tag="${date}_hybrid_${ttbar}_${zprime}_${size}"
else
    export samples="${eventtype}_${size}"
    export tag="${date}_${eventtype}_${size}"
fi

trainingsuffix='puCut0_tm0_stat1200k_cStat600k_BdtGrad_bin_cuts200_depth30_nTrees1000_MNS005_c07'
if [[ -n $hybridtuning ]]; then trainingsuffix="${trainingsuffix}_HybridTune"; fi
export trainingsuffix
export trainingprefix='MV2_gsc35'
export trainingtemplate='MV2_gsc35_FLo_20180522_puCut0_tm0_stat1200k_cStat600k_BdtGrad_bin_cuts200_depth30_nTrees1000_MNS005_c07_HybridTune.varlist'
export jobidregex='s/Submitted batch job \([0-9]\+\)/\1/p'

echo -e '\nSTEP 1.1\n'; bash retune_step1.1.sh
echo -e '\nSTEP 1.2\n'; bash retune_step1.2.sh
echo -e '\nSTEP 2\n'; bash retune_step2.sh
echo -e '\nSTEP 3.1\n'; bash retune_step3.1.sh
echo -e '\nSTEP 3.2\n'; bash retune_step3.2.sh
echo -e '\nSTEP 4\n'; bash retune_step4.sh
